# Language
# need reload to enable
# please write the file name with suffix
lang: "zh_cn.yml"

# Write模式下，投票的等待时间(秒)
# 需要reload启用
# Write Mode, Time for voting(seconds)
# need reload to enable
Write-wait-time: 30

